In [ ]:
Numpy
.numerical python or numeric python
.numpy is a programming language that deals with multi-dimensional arrays and matrices
.numpy supports a large number of mathematical operations
why use numpy
.numpy is memory efficiency meaning it can handle the vast amount of data more accessible than
any other library
.especially for matrix multiplication and reshaping
.on top of that,numpy is fast,in fact,tensorflow and scikit
how to install python
.numpy is installed by default in anaconda

In [7]:
import numpy as np

In [8]:
print(np.__version__)

1.19.2


In [9]:
# one dimensional array
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [10]:
print(np.array([2,4,6,8]))

[2 4 6 8]


In [9]:
# have to take two list in single one
# two dimensional array
data=np.array([[1,2,3,4],[5,6,7,8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# mathematical operations
a1=np.array([3,5,7,9])
a2=np.array([2,4,6,8])
print(a1+a2)
print(a1-a2)

[ 5  9 13 17]
[1 1 1 1]


In [14]:
# shape of the array
data=np.array([[1,2,3,4],[5,6,7,8]])
print(np.shape(data))
print(data.dtype)

(2, 4)
int32


In [17]:
data1=np.array([[1.1,2.2,3.3],[5.5,6.6,7.7]])
print(np.shape(data1))
print(data1.dtype)

(2, 3)
float64


In [27]:
#numpy zeroes and ones
#numpy zeroes
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [12]:
#numpy reshape
data2=np.array([[1,2,3,4],[6,7,8,9]])
print(data2)
data2.reshape((4,2))

[[1 2 3 4]
 [6 7 8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [19]:
# numpy flatten
print(data2)
data2.flatten()

[[1 2 3 4]
 [6 7 8 9]]


array([1, 2, 3, 4, 6, 7, 8, 9])

In [20]:
#numpy hstack->data horizontal append
print(a1)
print(a2)
np.hstack((a1,a2))

[3 5 7 9]
[2 4 6 8]


array([3, 5, 7, 9, 2, 4, 6, 8])

In [21]:
#vstack
print(a1)
print(a2)
np.vstack((a1,a2))

[3 5 7 9]
[2 4 6 8]


array([[3, 5, 7, 9],
       [2, 4, 6, 8]])

In [29]:
#vstack single variable
print(a1)
np.vstack((a1))

[3 5 7 9]


array([[3],
       [5],
       [7],
       [9]])

In [30]:
#hstack single variable
print(a2)
np.hstack((a2))

[2 4 6 8]


array([2, 4, 6, 8])

In [22]:
np.hstack((a1,a2))

array([3, 5, 7, 9, 2, 4, 6, 8])

In [24]:
a=np.array([2,3,4,5,6])
b=np.array([7,8,9,10])
np.vstack((a))

array([[2],
       [3],
       [4],
       [5],
       [6]])

In [31]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,4,5],[3,5,8]])
print(np.hstack((a,b)))

[[1 2 3 2 4 5]
 [4 5 6 3 5 8]]


In [25]:
# to calculate mean
print(data2)
data2.mean()

[[1 2 3 4]
 [6 7 8 9]]


5.0

In [26]:
# stand.deviation
print(data1)
data1.std()


[[1.1 2.2 3.3]
 [5.5 6.6 7.7]]


2.3762715894162154

In [ ]:
#to calculate mean,->
 

In [33]:
#generate random numbers
d=np.random.randint(1,3,(5,4))

In [34]:
d

array([[1, 2, 2, 1],
       [2, 2, 1, 1],
       [2, 2, 2, 2],
       [2, 1, 1, 2],
       [2, 2, 2, 2]])

In [40]:
#syntax:np.random.normal(loc(mean),scale(std),size)
np.random.randint(5,size=10)

array([3, 3, 4, 4, 0, 3, 3, 4, 4, 2])

In [35]:
np.random.normal(5,6,7)

array([-1.68554386, -2.7523835 , -1.71323114,  0.91563895, 13.08215614,
        6.97817897, 12.86455277])

In [36]:
# numpy statistical functions(min,max,mean,std)
d.mean()


1.7

In [37]:
d.min()


1

In [38]:
d.max()

2

In [39]:
d.std()

0.45825756949558394

In [41]:
#tarnspose 
print(d)
d.T

[[1 2 2 1]
 [2 2 1 1]
 [2 2 2 2]
 [2 1 1 2]
 [2 2 2 2]]


array([[1, 2, 2, 2, 2],
       [2, 2, 2, 1, 2],
       [2, 1, 2, 1, 2],
       [1, 1, 2, 2, 2]])

In [42]:
#3 rows 3 columns
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(4,dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
print(a1)
print(a2)
a1.dot(a2)

[3 5 7 9]
[2 4 6 8]


140

In [45]:
d1=np.array([1,2,3,4])
np.array([d1,pow(d1,3)])

array([[ 1,  2,  3,  4],
       [ 1,  8, 27, 64]])

In [46]:
#repeat
a=np.repeat([1,2,3,4],3)

In [47]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [48]:
#Arange function
#syntax --->arange(start,stop,step)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [50]:
#factorial of a number
a=np.math.factorial(5)
a

120

In [51]:
#numpy linspace(default=50)
#styntax:---->linspace(start,stop,num,endpoint)
np.linspace(1,5,num=10)


array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [53]:
#indexing slicing
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
x[0]#first row

array([1, 2, 3])

In [55]:
x[1]#second row

array([4, 5, 6])

In [56]:
print(x)
x[:,1]


[[1 2 3]
 [4 5 6]]


array([2, 5])